$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: garment-sam2-refine-env
description: SAM2 refine environment (GPU-ready)
image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
conda_file: conda.yaml
