$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: garment-yolo-seg
code_configuration:
  code: ./
  scoring_script: score.py
environment: azureml:garment-yolo-seg-env@latest
environment_variables:
  YOLO_WEIGHTS: yolov8l-seg.pt
instance_type: Standard_NC4as_T4_v3
instance_count: 1
request_settings:
  request_timeout_ms: 180000
